### ISSUE TITLE
Mismatch between filename and it's URL in generate_linter_fail_report.py

### ISSUE THREAD

**Issue by demin-han** [patrick-rivos/riscv-gnu-toolchain#479]
def generate_markdown(linter_log: str, patch_name: str, outdir: str="./linter_fail_report.md"):
    header = f"""
The following issues have been found with {patch_name} using gcc's [./contrib/check_GNU_style.py](https://github.com/gcc-mirror/gcc/blob/master/contrib/check_GNU_style.sh).
Please use your best judgement when resolving these issues. These are only warnings and do not need to be resolved in order to merge your patch.
If any of these warnings seem like false-positives that could be guarded against please contact me: patchworks-ci@rivosinc.com.

"""
URL should be:
(https://github.com/gcc-mirror/gcc/blob/master/contrib/check_GNU_style.py).

**Comment by patrick-rivos** [comment]
Thanks for catching this! It should be fixed now.
